%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
#debug模式
IfDebug: 1

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 762.72
Camera.fy: 762.72
Camera.cx: 640
Camera.cy: 360

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 20.0

# stereo baseline times fx
Camera.bf: 53.3904

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 720
LEFT.width: 1280
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0,0,0,0, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [762.72, 0.0, 640.0828882065675, 0.0, 762.72, 360.3515546907214, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9990515823722999, -0.0032556971385073966, 0.0434204582604347, 0.0032855622287763283, 0.9999944125102124, -0.0006164650807739699, -0.04341820862546814, 0.0007585410320411453, 0.9990566969773327]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [762.72, 0.0, 640, 0.0, 0.0, 762.72, 360, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 720
RIGHT.width: 1280
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0,0,0,0, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [762.72, 0.0, 640, 0.0, 762.72, 360, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.998890896747112, -0.0033889793702504135, 0.046962657660940765, 0.0033566749814764197, 0.9999940724193407, 0.0007667197995104152, -0.04696497768358282, -0.0006082310500526033, 0.9988963514430165]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [762.721, 0.0, 640, -53.3904, 0.0, 762.72, 360, 0.0, 0.0, 0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

DictPath: "/home/jena/csq_ws/src/px4_csq/Vocabulary/new_voc.bin"
model_path: "/home/jena/csq_ws/src/px4_csq/Vocabulary/stats.vstats"
use_ros_sub : 1
