// Generated by gencpp from file orb_formation/feature.msg
// DO NOT EDIT!


#ifndef ORB_FORMATION_MESSAGE_FEATURE_H
#define ORB_FORMATION_MESSAGE_FEATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace orb_formation
{
template <class ContainerAllocator>
struct feature_
{
  typedef feature_<ContainerAllocator> Type;

  feature_()
    : header()
    , tframe(0.0)
    , nrobotid(0)
    , data()  {
    }
  feature_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tframe(0.0)
    , nrobotid(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _tframe_type;
  _tframe_type tframe;

   typedef int16_t _nrobotid_type;
  _nrobotid_type nrobotid;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::orb_formation::feature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orb_formation::feature_<ContainerAllocator> const> ConstPtr;

}; // struct feature_

typedef ::orb_formation::feature_<std::allocator<void> > feature;

typedef boost::shared_ptr< ::orb_formation::feature > featurePtr;
typedef boost::shared_ptr< ::orb_formation::feature const> featureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orb_formation::feature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orb_formation::feature_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace orb_formation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'orb_formation': ['/home/jena/csq_ws/src/orb_formation/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::orb_formation::feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orb_formation::feature_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_formation::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orb_formation::feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_formation::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orb_formation::feature_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orb_formation::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f479cc2f4feb5562e889083a5793916";
  }

  static const char* value(const ::orb_formation::feature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f479cc2f4feb556ULL;
  static const uint64_t static_value2 = 0x2e889083a5793916ULL;
};

template<class ContainerAllocator>
struct DataType< ::orb_formation::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orb_formation/feature";
  }

  static const char* value(const ::orb_formation::feature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orb_formation::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 tframe\n\
int16 nrobotid\n\
byte[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::orb_formation::feature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orb_formation::feature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tframe);
      stream.next(m.nrobotid);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orb_formation::feature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::orb_formation::feature_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tframe: ";
    Printer<double>::stream(s, indent + "  ", v.tframe);
    s << indent << "nrobotid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.nrobotid);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ORB_FORMATION_MESSAGE_FEATURE_H
