// Generated by gencpp from file px4_csq/gs_command.msg
// DO NOT EDIT!


#ifndef PX4_CSQ_MESSAGE_GS_COMMAND_H
#define PX4_CSQ_MESSAGE_GS_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace px4_csq
{
template <class ContainerAllocator>
struct gs_command_
{
  typedef gs_command_<ContainerAllocator> Type;

  gs_command_()
    : mission_type(0)
    , start(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  gs_command_(const ContainerAllocator& _alloc)
    : mission_type(0)
    , start(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _mission_type_type;
  _mission_type_type mission_type;

   typedef uint8_t _start_type;
  _start_type start;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::px4_csq::gs_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px4_csq::gs_command_<ContainerAllocator> const> ConstPtr;

}; // struct gs_command_

typedef ::px4_csq::gs_command_<std::allocator<void> > gs_command;

typedef boost::shared_ptr< ::px4_csq::gs_command > gs_commandPtr;
typedef boost::shared_ptr< ::px4_csq::gs_command const> gs_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px4_csq::gs_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px4_csq::gs_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px4_csq

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'px4_csq': ['/home/jena/csq_ws/src/px4_csq/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px4_csq::gs_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px4_csq::gs_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_csq::gs_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px4_csq::gs_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_csq::gs_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px4_csq::gs_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px4_csq::gs_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65ebd6a487eda76da820d2501d6386c1";
  }

  static const char* value(const ::px4_csq::gs_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65ebd6a487eda76dULL;
  static const uint64_t static_value2 = 0xa820d2501d6386c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::px4_csq::gs_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px4_csq/gs_command";
  }

  static const char* value(const ::px4_csq::gs_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px4_csq::gs_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 mission_type\n\
##0 arm 1 takeoff 2 moveTo 3 mission\n\
bool start\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 yaw\n\
";
  }

  static const char* value(const ::px4_csq::gs_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px4_csq::gs_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_type);
      stream.next(m.start);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gs_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px4_csq::gs_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px4_csq::gs_command_<ContainerAllocator>& v)
  {
    s << indent << "mission_type: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mission_type);
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX4_CSQ_MESSAGE_GS_COMMAND_H
